[project]
name = "varphi-interpreter"
version = "3.0.1"
description = "An all-in-one tool for compiling and interpreting Varphi programs."
readme = "README.md"
authors = [
    { name = "Varphi", email = "support@varphi-lang.com" }
]
requires-python = ">=3.10"
dependencies = [
    "typer>=0.21.0",
    "vp2py>=3.0.0",
    "vp2pydap>=3.0.0",
]

[project.scripts]
vpi = "varphi_interpreter.cli:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black",
    "pillow>=12.3.0",
    "pyinstaller>=6.22.2",
    "requests>=2.34.2",
    "vermin",
]
